### ISSUE TITLE
Allow Windows 8.1 To be Edited

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [E-Sh4rk/KuruTools#6]
I have a glitchy windows 10 that won't run dotnet programs and like 5d chess it only runs on windows 10

**Comment by E-Sh4rk** [comment]
Hi!
What exactly prevents you from running it on Windows 8.1?
.NET Core 3.1 should be compatible with Windows 7, 8, 8.1 and 10.
